---
docker_package_name: "{% if ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' %} docker-engine {% else %} docker-ce {% endif %}"
docker_package_state: installed

docker_service_name: docker
docker_service_state: started
docker_service_enabled: true
docker_services:
- name: docker.socket
  enabled: '{{ docker_service_enabled }}'
  state: '{{ docker_service_state }}'
- name: docker.service
  enabled: '{{ docker_service_enabled }}'
  state: '{{ docker_service_state }}'

docker_data_dir: /var/lib/docker
docker_yum_repo_url: https://yum.dockerproject.org/repo/main/centos/{{ ansible_distribution_major_version }}

docker_bridge_ip: "172.19.1.1"
docker_bridge_cidr: "{{docker_bridge_ip}}/16"


docker_additional_options: ""
docker_options: >
  --insecure-registry 0.0.0.0/0 --bip={{docker_bridge_cidr}} --exec-opt native.cgroupdriver=cgroupfs {{docker_additional_options}}

docker_yum_repo_template_file: docker.repo.j2
docker_dropin_template_file: docker.dropin.j2
docker_config_path: /etc/systemd/system/docker.service.d
docker_config_file: '{{ docker_config_path }}/overrideexec.conf'

# install docker-python using pip. The 1.7.2 seems to work with a recent ansible 1.9
# this is needed for the ansible "docker" module. You need to install epel and pip before
docker_python: false
docker_python_version: 1.7.2

docker_socket_template_file: docker.socket.j2
docker_socket_file: /usr/lib/systemd/system/docker.socket
